name: Docker Image CI

on:
  workflow_run:
    workflows: [Java CI with Maven]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Maven Jar
      uses: actions/download-artifact@v4
      with:
        name: demo-snapshot-jar

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paulienvanalst/demo-helm:$(date +%s)
